spring:
  application:
    name: buyathome
  datasource:
    name: buyathome
    platform: mysql
    url: jdbc:mysql://localhost:3306/buyathome?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 2208
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000

logging:
  level:
    com:
      spring:
        ibatis:
          UserMapper=DEBUG:
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/dao/*Dao.xml